### PR TITLE
Add policy visualization tool

### PR DESCRIPTION
**Pull request by prob1995**
I wrote a policy visualization tool trying to reproduce the figure in the paper. This may help people to understand the policy schedule more easier.

### CODE REVIEW

**Comment by arcelien** [comment]
This is awesome! Thanks a lot for your contribution.

**Comment by chichan01** [comment]
There is something wrong on the tool of policy visualization
In augmentation_transforms_hp.py
line 64:   name, probability, level = xform
However, in Policy_visualization.ipynb
        for i in parsed_policy[:half_policy]:
            upper_magnitude[i[0]].append(i[1]) 
            upper_probability[i[0]].append(i[2])
        for i in parsed_policy[half_policy:]:
            bottom_magnitude[i[0]].append(i[1]) 
            bottom_probability[i[0]].append(i[2])
It means that it is (name, magnitude, probability).. which is not similar to the configuration on augmentation_transforms_hp.py

**Comment by prob1995** [comment]
@chichan01  Looks like I made a mistake. It can be corrected by changing index from 1 to 2 and vice versa. Will make a PR later to correct it.  @chichan01 Thank you for pointing this out!

**Comment by chichan01** [comment]
another thing I would like to recommend is that if the probability is 0, you can also set the magnitude to be zero.. and also if the magnitude is zero, set the probability to zero as well.
________________________________

**Pull request merged**
